# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          wget https://talonvoice.com/dl/latest/talon-mac.dmg
          sudo hdiutil attach talon-mac.dmg
          sudo cp -R /Volumes/Talon/Talon.app /Applications
          sudo hdiutil unmount  /Volumes/Talon
          sudo xattr -d -r com.apple.quarantine /Applications/Talon.app
          open /Applications/Talon.app
          sleep 20
          ps uax | grep Talon
          cat ~/.talon/*.log
  
